DROP TABLE MEMBER CASCADE CONSTRAINTS;
DROP TABLE ITEM CASCADE CONSTRAINTS;
DROP TABLE PURCHASEDITEM CASCADE CONSTRAINTS;
DROP TABLE BOARDCODE CASCADE CONSTRAINTS;
DROP TABLE BOARD CASCADE CONSTRAINTS;
DROP TABLE BOARDPOINT CASCADE CONSTRAINTS;
DROP TABLE ATTACHFILE CASCADE CONSTRAINTS;
DROP TABLE COMMENTS CASCADE CONSTRAINTS;
DROP TABLE COMMENTSPOINT CASCADE CONSTRAINTS;
DROP TABLE REPORTLIST CASCADE CONSTRAINTS;
DROP TABLE CREPORTLIST CASCADE CONSTRAINTS;
DROP TABLE ITEMMOOD CASCADE CONSTRAINTS;
DROP TABLE WEEKSUBJECT CASCADE CONSTRAINTS;
DROP TABLE PROLIST CASCADE CONSTRAINTS;
DROP TABLE CONLIST CASCADE CONSTRAINTS;
DROP TABLE LEVELING;


--멤버
CREATE TABLE MEMBER
(
    MEMBERCODE NUMBER PRIMARY KEY,
    ID VARCHAR2(20) UNIQUE NOT NULL,
    PASSWORD VARCHAR2(20) NOT NULL,
    EMAIL VARCHAR2(30) UNIQUE NOT NULL,
    PHOTO VARCHAR2(200),
    MEDAL NUMBER NOT NULL,
    HAVMEDAL NUMBER NOT NULL,
    EXP NUMBER NOT NULL,
    CASH NUMBER NOT NULL,
    DDARU NUMBER NOT NULL,
    REPORT NUMBER NOT NULL,
    RECOMPOINT NUMBER NOT NULL,
    JOB VARCHAR2(24),
    ENROLLDATE DATE DEFAULT SYSDATE NOT NULL,
    QUITDATE DATE
);

CREATE TABLE LEVELING
(
    LEV NUMBER PRIMARY KEY,
    EXP NUMBER NOT NULL
);
INSERT INTO LEVELING VALUES(LEV_SEQ.NEXTVAL,1);
COMMIT;

DECLARE
    LP NUMBER:=1;
    MULTI NUMBER:=2;
BEGIN
    LOOP       
        IF LP>=75 THEN MULTI:=1.1;
        ELSIF LP>=50 THEN MULTI:=1.2;
        ELSIF LP>=25 THEN MULTI:=1.5;
        END IF;
        
        INSERT INTO LEVELING VALUES(LEV_SEQ.NEXTVAL,FLOOR((SELECT MAX(EXP) FROM LEVELING)*MULTI));
        LP:=LP+1;
        
        EXIT WHEN LP>=100;
    END LOOP;       
END;
/
--아이템
CREATE TABLE ITEMMOOD
(
    MOOD NUMBER NOT NULL PRIMARY KEY,
    NAME VARCHAR(30) NOT NULL
);

CREATE TABLE ITEM
(
    ITEMCODE NUMBER PRIMARY KEY,
    NAME VARCHAR2(30) NOT NULL,
    USAGEDATE NUMBER NOT NULL,
    MOOD NUMBER NOT NULL,
    FILELINK VARCHAR2(100) NOT NULL,
    PRICE NUMBER NOT NULL,
    CONSTRAINT ITEM_MOOD FOREIGN KEY (MOOD) REFERENCES ITEMMOOD (MOOD)
);

CREATE TABLE PURCHASEDITEM
(
    MEMBERCODE NUMBER,
    ITEMCODE NUMBER,
    PURCHASEDATE DATE NOT NULL,
    CONSTRAINT PK_MEMBER_ITEM PRIMARY KEY(MEMBERCODE,ITEMCODE),
    CONSTRAINT FK_MEMBER FOREIGN KEY (MEMBERCODE) REFERENCES MEMBER (MEMBERCODE),
    CONSTRAINT FK_ITEM FOREIGN KEY (ITEMCODE) REFERENCES ITEM (ITEMCODE)
);

--게시글
CREATE TABLE BOARDCODE
(
    DISCODE NUMBER PRIMARY KEY,
    NAME VARCHAR2(20)
);

CREATE TABLE BOARD
(
    BCODE NUMBER PRIMARY KEY,
    TITLE VARCHAR2(200) NOT NULL,
    CONTENT  VARCHAR2(4000),
    DISTINGUISH  NUMBER NOT NULL,
    WRITERID  VARCHAR2(20) NOT NULL,
    POSTDATE DATE DEFAULT SYSDATE NOT NULL ,
    ISDELETE CHAR(1),
    HASFILE CHAR(1),
    CONSTRAINT FK_ID_BOARD FOREIGN KEY (WRITERID) REFERENCES MEMBER (ID),
    CONSTRAINT FK_DISTINGUISH FOREIGN KEY (DISTINGUISH) REFERENCES BOARDCODE (DISCODE)
);

CREATE TABLE BOARDPOINT
(
    BCODE NUMBER PRIMARY KEY,
    VIEWNUM NUMBER DEFAULT 0 NOT NULL,
    BEST NUMBER DEFAULT 0 NOT NULL,
    GOOD NUMBER DEFAULT 0 NOT NULL,
    BAD NUMBER DEFAULT 0 NOT NULL,
    WORST NUMBER DEFAULT 0 NOT NULL,
    CAL NUMBER DEFAULT 0 NOT NULL,
    MEDAL NUMBER DEFAULT 0 NOT NULL,
    REPORT NUMBER DEFAULT 0 NOT NULL,
    CONSTRAINT FK_BOARDPOINT FOREIGN KEY (BCODE) REFERENCES BOARD (BCODE)
);
--첨부파일
CREATE TABLE ATTACHFILE
(
    ATCODE NUMBER PRIMARY KEY,
    ORIGINNAME VARCHAR2(1000) NOT NULL,
    CHANGEDNAME  VARCHAR2(1000) NOT NULL,
    BCODE NUMBER,
    FILELINK  VARCHAR2(2000) NOT NULL,
    CONSTRAINT FK_ATTA_BOARD FOREIGN KEY (BCODE) REFERENCES BOARD (BCODE)    
);
--댓글
CREATE TABLE COMMENTS
(
    CCODE NUMBER PRIMARY KEY,
    CONTENT VARCHAR2(600),
    WRITERID VARCHAR2(20) NOT NULL,
    POSTDATE DATE DEFAULT SYSDATE NOT NULL,
    LEV NUMBER NOT NULL,
    UPPER NUMBER,
    BCODE NUMBER NOT NULL,
    CONSTRAINT FK_COMMENT_BOARD FOREIGN KEY (BCODE) REFERENCES BOARD (BCODE),
    CONSTRAINT FK_COMMENT FOREIGN KEY (UPPER) REFERENCES COMMENTS (CCODE),
    CONSTRAINT FK_COMMENT_ID FOREIGN KEY (WRITERID) REFERENCES MEMBER (ID)  
);

CREATE TABLE COMMENTSPOINT
(
    CCODE NUMBER PRIMARY KEY,
    GOOD NUMBER DEFAULT 0 NOT NULL,
    BAD NUMBER DEFAULT 0 NOT NULL,
    CAL NUMBER DEFAULT 0 NOT NULL,
    MEDAL NUMBER DEFAULT 0 NOT NULL,
    REPORT NUMBER DEFAULT 0 NOT NULL,
    CONSTRAINT FK_COMMENTSPOINT FOREIGN KEY (CCODE) REFERENCES COMMENTS (CCODE)
);
--신고 리스트
CREATE TABLE REPORTLIST
(
    BCODE NUMBER NOT NULL,
    ID VARCHAR2(20) NOT NULL,
    CONSTRAINT REP_BCODE FOREIGN KEY (BCODE) REFERENCES BOARD (BCODE),
    CONSTRAINT REP_ID FOREIGN KEY (ID) REFERENCES MEMBER (ID),
    CONSTRAINT REP_PK PRIMARY KEY (BCODE,ID)
);

CREATE TABLE CREPORTLIST
(
    CCODE NUMBER NOT NULL,
    ID VARCHAR2(20) NOT NULL,
    CONSTRAINT CREP_CCODE FOREIGN KEY (CCODE) REFERENCES COMMENTS (CCODE),
    CONSTRAINT CREP_ID FOREIGN KEY (ID) REFERENCES MEMBER (ID),
    CONSTRAINT CREP_PK PRIMARY KEY (CCODE,ID)
);

--신기술 주제
CREATE TABLE WEEKSUBJECT
(
    WSCODE NUMBER PRIMARY KEY,
    TITLE VARCHAR2(100) NOT NULL,
    STARTDATE DATE NOT NULL    
);

--신기술 찬반 리스트
CREATE TABLE PROLIST
(
    WSCODE NUMBER PRIMARY KEY,
    ID VARCHAR2(11),
    CONSTRAINT PL_ID FOREIGN KEY (ID) REFERENCES MEMBER(ID)
);

CREATE TABLE CONLIST
(
    WSCODE NUMBER PRIMARY KEY,
    ID VARCHAR2(11),
    CONSTRAINT CL_ID FOREIGN KEY (ID) REFERENCES MEMBER(ID)
);