DROP TABLE SERVICE;

CREATE TABLE SERVICE(
  SERNAME	VARCHAR2(20 BYTE) NOT NULL,
  SERADD	VARCHAR2(100 BYTE) NOT NULL,
  SERTITLE VARCHAR2(1000 BYTE),
  SERCONTENT	VARCHAR2(3000 BYTE)NOT NULL,
  SERDATE DATE DEFAULT SYSDATE,
  YNCHECK	CHAR(2 BYTE) CHECK (YNCHECK IN('Y','N'))  
);
select * from service;

COMMIT;